from quick_sort import quick_sort
from binary_search import binary_search

if __name__ == "__main__":

    data = [
        "Elana",
        "Jessica",
        "Dianne",
        "Nathalie",
        "Ludie",
        "Floy",
        "Leland",
        "Liliana",
        "Jermaine",
        "Mallory",
        "Darla",
        "Abram",
        "Thresa",
        "Zachery",
        "Antoinette",
        "Shaunta",
        "Nova",
        "Liana",
        "Tami",
        "Kayla",
        "Ethel",
        "Felecia",
        "Chu",
        "So",
        "Agustina",
        "Erwin",
        "Angelita",
        "Flora",
        "Shellie",
        "Alice",
        "Merlin",
        "Kathlene",
        "Samella",
        "Mica",
        "Jamee",
        "Tatum",
        "Carmen",
        "Dalton",
        "Arden",
        "Toni",
        "Fatima",
        "Agatha",
        "Rosalva",
        "Araceli",
        "Felicitas",
        "Eveline",
        "Xiomara",
        "Mauricio",
        "Tarra",
    ]

    print(quick_sort(data))
    print(binary_search(quick_sort(data), "Agustina"))
